server {
    listen 80;
    server_name admin.localhost;
    client_max_body_size 20M;

    root /var/www/backend/laravel/public;
        index index.php;

    location = / {
        return 301 /admin;
    }


    location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

    location ~ \.php$ {
         include fastcgi_params;
         fastcgi_pass php:9000;
         fastcgi_param SCRIPT_FILENAME /var/www/backend/laravel/public$fastcgi_script_name;
         fastcgi_connect_timeout 60;
                    fastcgi_send_timeout 180;
                    fastcgi_read_timeout 180;
                    fastcgi_buffer_size 128k;
                    fastcgi_buffers 4 256k;
                    fastcgi_busy_buffers_size 256k;
                    fastcgi_temp_file_write_size 256k;
    }
}