server {
    listen 80;
    server_name localhost;
    client_max_body_size 20M;

    # Laravel root
    root /var/www/backend/laravel/public;
    index index.php;

    #API
   location ^~ /api/ {
           fastcgi_pass php:9000;
           include fastcgi_params;
           fastcgi_param SCRIPT_FILENAME $document_root/index.php;
           fastcgi_param SCRIPT_NAME /index.php;
           fastcgi_param REQUEST_URI $uri?$args;
           fastcgi_connect_timeout 60;
           fastcgi_send_timeout 180;
           fastcgi_read_timeout 180;
           fastcgi_buffer_size 128k;
           fastcgi_buffers 4 256k;
           fastcgi_busy_buffers_size 256k;
           fastcgi_temp_file_write_size 256k;
       }

    #PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/laravel/public$fastcgi_script_name;
    }

    #Vue
    location / {
        alias /var/www/frontend/dist/;
        index index.html;
        try_files $uri $uri/ @spa;
    }

    location @spa {
        rewrite ^ /index.html last;
    }
}
